apiVersion: apps/v1
kind: Deployment
metadata:
  name: knn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knn
  template:
    metadata:
      labels:
        app: knn
    spec:
      containers:
      - name: knn
        image: "tsawler/knn:1.0.1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: knn
spec:
  selector:
    app: knn
  ports:
    - protocol: TCP
      name: web-port
      port: 80
      targetPort: 80